# Generated by Django 4.1.7 on 2023-03-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Regno',
            field=models.IntegerField(),
        ),
    ]
