# Generated by Django 4.1.7 on 2023-03-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTask', '0002_alter_student_regno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('lectureName', models.CharField(max_length=100)),
            ],
        ),
    ]
