# Generated by Django 4.1.7 on 2023-03-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTask', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=200)),
                ('Regno', models.IntegerField()),
                ('course', models.CharField(max_length=200)),
            ],
        ),
    ]
