# Generated by Django 4.1.7 on 2023-03-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTask', '0004_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', max_length=1028, upload_to=''),
        ),
    ]
