# Generated by Django 4.1.7 on 2023-03-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTask', '0008_result_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseId',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
