# Generated by Django 4.1.7 on 2023-03-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstTask', '0009_course_courseid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Regno', models.IntegerField()),
                ('attendence', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='courseId',
            field=models.CharField(default='', max_length=100),
        ),
    ]
